version: '3.8'
services:
  db:
    container_name: pg12
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    network_mode: host
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
volumes:
  db:
    driver: local